server.port: 8086
spring:
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop?serverTimezone=UTC
    username: onlineshop
    password: onlineshop